function ImageEnhancementGUI()

    originalImage = [];
    enhancedImage = [];

    darkBlue   = [0.05 0.12 0.22];
    blue       = [0.10 0.25 0.45];
    lightBlue  = [0.20 0.40 0.65];

    white      = [1 1 1];
    lightGray  = [0.94 0.96 0.98];
    borderGray = [0.65 0.70 0.78];

    fig = uifigure( ...
        'Name', 'Image Enhancement Application', ...
        'Position', [100 100 1200 750], ...
        'Color', lightGray);

    titleLabel = uilabel(fig, ...
        'Text', 'Enhanctress Image Enhancer', ...
        'FontSize', 20, ...
        'FontWeight', 'bold', ...
        'FontColor', white, ...
        'HorizontalAlignment', 'center', ...
        'BackgroundColor', darkBlue, ...
        'Position', [0 700 1200 50]);

    controlPanel = uipanel(fig, ...
        'Position', [20 585 1160 100], ...
        'BackgroundColor', white, ...
        'BorderType', 'line', ...
        'BorderWidth', 1, ...
        'BorderColor', borderGray);

    openButton = uibutton(controlPanel, ...
        'Text', 'Open Image', ...
        'FontWeight', 'bold', ...
        'FontColor', white, ...
        'BackgroundColor', blue, ...
        'Position', [15 52 120 30], ...
        'ButtonPushedFcn', @openImage);


    imageNameLabel = uilabel(controlPanel, ...
        'Text', 'No image selected', ...
        'FontColor', blue, ...
        'Position', [150 52 330 30]);

    enhancementLabel = uilabel(controlPanel, ...
        'Text', 'Enhancement Technique', ...
        'FontWeight', 'bold', ...
        'FontColor', blue, ...
        'Position', [500 58 150 25]);


    enhancementDropdown = uidropdown(controlPanel, ...
        'Items', { ...
        'Image Brightening', ...
        'Contrast Stretching', ...
        'Gamma Correction', ...
        'Histogram Equalization', ...
        'Median Filter', ...
        'Gaussian Filter'}, ...
        'FontColor', darkBlue, ...
        'BackgroundColor', lightGray, ...
        'Position', [650 58 200 30], ...
        'ValueChangedFcn', @changeTechnique);

    parameterLabel = uilabel(controlPanel, ...
        'Text', 'Brightness:', ...
        'FontColor', blue, ...
        'FontWeight', 'bold', ...
        'Position', [500 15 80 25]);


    parameterField = uieditfield(controlPanel, 'numeric', ...
        'Value', 50, ...
        'FontColor', darkBlue, ...
        'BackgroundColor', lightGray, ...
        'Position', [580 15 80 30]);

    parameterLabel2 = uilabel(controlPanel, ...
        'Text', 'Sigma:', ...
        'FontColor', blue, ...
        'FontWeight', 'bold', ...
        'Position', [675 15 50 25], ...
        'Visible', 'off');


    parameterField2 = uieditfield(controlPanel, 'numeric', ...
        'Value', 1, ...
        'FontColor', darkBlue, ...
        'BackgroundColor', lightGray, ...
        'Position', [725 15 70 30], ...
        'Visible', 'off');

    applyButton = uibutton(controlPanel, ...
        'Text', 'Apply Enhancement', ...
        'FontWeight', 'bold', ...
        'FontColor', white, ...
        'BackgroundColor', lightBlue, ...
        'Position', [870 15 135 30], ...
        'ButtonPushedFcn', @applyEnhancement);

    saveButton = uibutton(controlPanel, ...
        'Text', 'Save Image', ...
        'FontWeight', 'bold', ...
        'FontColor', white, ...
        'BackgroundColor', blue, ...
        'Position', [1015 15 120 30], ...
        'ButtonPushedFcn', @saveImage);

    originalPanel = uipanel(fig, ...
        'Title', 'Original Image', ...
        'FontWeight', 'bold', ...
        'ForegroundColor', blue, ...
        'BackgroundColor', white, ...
        'BorderType', 'line', ...
        'BorderWidth', 1, ...
        'BorderColor', borderGray, ...
        'Position', [20 330 570 240]);


    originalAxes = uiaxes(originalPanel, ...
        'Position', [10 10 550 200], ...
        'BackgroundColor', white, ...
        'XColor', blue, ...
        'YColor', blue);

    originalAxes.XTick = [];
    originalAxes.YTick = [];

    enhancedPanel = uipanel(fig, ...
        'Title', 'Enhanced Image', ...
        'FontWeight', 'bold', ...
        'ForegroundColor', blue, ...
        'BackgroundColor', white, ...
        'BorderType', 'line', ...
        'BorderWidth', 1, ...
        'BorderColor', borderGray, ...
        'Position', [610 330 570 240]);


    enhancedAxes = uiaxes(enhancedPanel, ...
        'Position', [10 10 550 200], ...
        'BackgroundColor', white, ...
        'XColor', blue, ...
        'YColor', blue);

    enhancedAxes.XTick = [];
    enhancedAxes.YTick = [];

    originalHistogramPanel = uipanel(fig, ...
        'Title', 'Original Histogram', ...
        'FontWeight', 'bold', ...
        'ForegroundColor', blue, ...
        'BackgroundColor', white, ...
        'BorderType', 'line', ...
        'BorderWidth', 1, ...
        'BorderColor', borderGray, ...
        'Position', [20 50 570 240]);


    originalHistogramAxes = uiaxes(originalHistogramPanel, ...
        'Position', [10 10 550 200], ...
        'BackgroundColor', white, ...
        'XColor', blue, ...
        'YColor', blue);

    xlabel(originalHistogramAxes, ...
        'Gray Level', ...
        'Color', blue);

    ylabel(originalHistogramAxes, ...
        'Pixels', ...
        'Color', blue);

    enhancedHistogramPanel = uipanel(fig, ...
        'Title', 'Enhanced Histogram', ...
        'FontWeight', 'bold', ...
        'ForegroundColor', blue, ...
        'BackgroundColor', white, ...
        'BorderType', 'line', ...
        'BorderWidth', 1, ...
        'BorderColor', borderGray, ...
        'Position', [610 50 570 240]);


    enhancedHistogramAxes = uiaxes(enhancedHistogramPanel, ...
        'Position', [10 10 550 200], ...
        'BackgroundColor', white, ...
        'XColor', blue, ...
        'YColor', blue);

    xlabel(enhancedHistogramAxes, ...
        'Gray Level', ...
        'Color', blue);

    ylabel(enhancedHistogramAxes, ...
        'Pixels', ...
        'Color', blue);

    function openImage(~, ~)

        [file, path] = uigetfile( ...
            {'*.jpg;*.jpeg;*.png;*.bmp;*.tif', ...
            'Image Files (*.jpg, *.jpeg, *.png, *.bmp, *.tif)'}, ...
            'Select an Image');


        if isequal(file, 0)
            return;
        end


        originalImage = imread(fullfile(path, file));

        enhancedImage = [];


        imageNameLabel.Text = file;


        imshow(originalImage, ...
            'Parent', originalAxes);

        title(originalAxes, ...
            'Original Image', ...
            'Color', blue);


        cla(enhancedAxes);

        title(enhancedAxes, ...
            'Enhanced Image', ...
            'Color', blue);


        displayHistogram( ...
            originalImage, ...
            originalHistogramAxes);


        cla(enhancedHistogramAxes);

        title(enhancedHistogramAxes, ...
            'Enhanced Histogram', ...
            'Color', blue);

    end

    function changeTechnique(~, ~)

        technique = enhancementDropdown.Value;

        parameterLabel2.Visible = 'off';
        parameterField2.Visible = 'off';


        switch technique

            case 'Image Brightening'

                parameterLabel.Text = 'Brightness:';

                parameterField.Value = 50;

                parameterLabel.Visible = 'on';
                parameterField.Visible = 'on';


            case 'Contrast Stretching'

                parameterLabel.Visible = 'off';
                parameterField.Visible = 'off';


            case 'Gamma Correction'

                parameterLabel.Text = 'Gamma:';

                parameterField.Value = 1;

                parameterLabel.Visible = 'on';
                parameterField.Visible = 'on';


            case 'Histogram Equalization'

                parameterLabel.Visible = 'off';
                parameterField.Visible = 'off';


            case 'Median Filter'

                parameterLabel.Text = 'Filter Size:';

                parameterField.Value = 3;

                parameterLabel.Visible = 'on';
                parameterField.Visible = 'on';


            case 'Gaussian Filter'

                parameterLabel.Text = 'Kernel:';

                parameterField.Value = 3;

                parameterLabel.Visible = 'on';
                parameterField.Visible = 'on';


                parameterLabel2.Text = 'Sigma:';

                parameterField2.Value = 1;

                parameterLabel2.Visible = 'on';
                parameterField2.Visible = 'on';

        end

    end

    function applyEnhancement(~, ~)

        if isempty(originalImage)

            uialert(fig, ...
                'Please open an image first.', ...
                'No Image');

            return;

        end


        technique = enhancementDropdown.Value;

        parameter = parameterField.Value;


        try

            switch technique

                case 'Image Brightening'

                    enhancedImage = ImageBrightening( ...
                        originalImage, ...
                        parameter);


                case 'Contrast Stretching'

                    enhancedImage = ContrastStretching( ...
                        originalImage);


                case 'Gamma Correction'

                    if parameter <= 0

                        error( ...
                            'Gamma must be greater than 0.');

                    end


                    enhancedImage = GammaCorrection( ...
                        originalImage, ...
                        parameter);


                case 'Histogram Equalization'

                    enhancedImage = HistogramEqualization( ...
                        originalImage);


                case 'Median Filter'

                    if parameter <= 0 || ...
                            mod(parameter, 2) ~= 1

                        error( ...
                            'Filter size must be a positive odd number.');

                    end


                    enhancedImage = MedianFilter( ...
                        originalImage);


                case 'Gaussian Filter'

                    filterSize = parameterField.Value;

                    sigma = parameterField2.Value;


                    if filterSize <= 0 || ...
                            mod(filterSize, 2) ~= 1

                        error( ...
                            'Kernel size must be a positive odd number.');

                    end


                    if sigma <= 0

                        error( ...
                            'Sigma must be greater than 0.');

                    end


                    enhancedImage = GaussianFilter( ...
                        originalImage, ...
                        filterSize, ...
                        sigma);

            end

            imshow(enhancedImage, ...
                'Parent', enhancedAxes);


            title(enhancedAxes, ...
                ['Enhanced Image - ' technique], ...
                'Color', blue);

            displayHistogram( ...
                enhancedImage, ...
                enhancedHistogramAxes);

        catch ME

            uialert(fig, ...
                ME.message, ...
                'Enhancement Error');

        end

    end

    function saveImage(~, ~)

        if isempty(enhancedImage)

            uialert(fig, ...
                'Please apply an enhancement first.', ...
                'No Enhanced Image');

            return;

        end


        [file, path] = uiputfile( ...
            {'*.png', 'PNG Image (*.png)'; ...
             '*.jpg', 'JPEG Image (*.jpg)'; ...
             '*.bmp', 'Bitmap Image (*.bmp)'}, ...
            'Save Enhanced Image');


        if isequal(file, 0)
            return;
        end


        imwrite( ...
            enhancedImage, ...
            fullfile(path, file));


        uialert(fig, ...
            'Enhanced image successfully saved.', ...
            'Success');

    end

    function displayHistogram(imageArray, axesHandle)

    % Memanggil fungsi HistogramImage
    [redCount, greenCount, blueCount] = ...
        HistogramImage(imageArray);

    cla(axesHandle);


    [~, ~, channels] = size(imageArray);

    if channels == 1

        bar( ...
            axesHandle, ...
            0:255, ...
            redCount, ...
            'BarWidth', 1);


        title( ...
            axesHandle, ...
            'Grayscale Histogram', ...
            'Color', blue);


        xlabel( ...
            axesHandle, ...
            'Gray Level', ...
            'Color', blue);


        ylabel( ...
            axesHandle, ...
            'Pixels', ...
            'Color', blue);
    elseif channels == 3

        isGrayscale = isequal( ...
            imageArray(:,:,1), ...
            imageArray(:,:,2)) && ...
            isequal( ...
            imageArray(:,:,2), ...
            imageArray(:,:,3));

        if isGrayscale

            bar( ...
                axesHandle, ...
                0:255, ...
                redCount, ...
                'BarWidth', 1);


            title( ...
                axesHandle, ...
                'Grayscale Histogram', ...
                'Color', blue);


            xlabel( ...
                axesHandle, ...
                'Gray Level', ...
                'Color', blue);


            ylabel( ...
                axesHandle, ...
                'Pixels', ...
                'Color', blue);

        else

            hold(axesHandle, 'on');


            plot( ...
                axesHandle, ...
                0:255, ...
                redCount, ...
                'LineWidth', 1);


            plot( ...
                axesHandle, ...
                0:255, ...
                greenCount, ...
                'LineWidth', 1);


            plot( ...
                axesHandle, ...
                0:255, ...
                blueCount, ...
                'LineWidth', 1);


            hold(axesHandle, 'off');


            title( ...
                axesHandle, ...
                'RGB Histogram', ...
                'Color', blue);


            xlabel( ...
                axesHandle, ...
                'Pixel Value', ...
                'Color', blue);


            ylabel( ...
                axesHandle, ...
                'Pixels', ...
                'Color', blue);


            legend( ...
                axesHandle, ...
                'Red', ...
                'Green', ...
                'Blue');

        end

    end

end

end